name:                calendar-formal
version:             0.1.0.0
github:              "githubuser/calendar-formal"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/calendar-formal#readme>

dependencies:
- base >= 4.7 && < 5
- regex-tdfa
# - regex-tdfa-text
- time
- cassava
- vector
- bytestring
- raw-strings-qq

library:
  source-dirs: src

executables:
  calendar-formal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calendar-formal

tests:
  calendar-formal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calendar-formal
