name:                daysoff-checker
version:             0.1.0.0
github:              "quimFIB/daysoff-checker"
license:             BSD3
author:              "Quim"
maintainer:          "quimFIB@github.com"
copyright:           "2022 quimFIB"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quimFIB/daysoff-checker#readme>

dependencies:
- base >= 4.7 && < 5
- regex-tdfa
# - regex-tdfa-text
- time
- cassava
- vector
- bytestring
- raw-strings-qq
- split
- transformers
- mtl

library:
  source-dirs: src

executables:
  daysoff-checker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - daysoff-checker
    - optparse-applicative >= 0.16

tests:
  daysoff-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - daysoff-checker
